xxxxxx

diff --git a/.github/workflows/Destroy.yaml b/.github/workflows/Destroy.yaml
--- a/.github/workflows/Destroy.yaml
+++ b/.github/workflows/Destroy.yaml
@@ -1,7 +1,12 @@
 name: Terraform Destroy Workflow
 
 on:
-  workflow_dispatch: # Permite iniciar manualmente el workflow desde la UI de GitHub
+  workflow_dispatch:
+    inputs:
+      confirm_destroy:
+        description: 'Type "yes" to confirm destruction'
+        required: true
+        default: 'no'
 
 jobs:
   terraform-destroy:
@@ -15,7 +20,7 @@ jobs:
     - name: Set up Terraform
       uses: hashicorp/setup-terraform@v2
       with:
-        terraform_version: 1.5.0 # Cambia según la versión que utilices
+        terraform_version: 1.8.4
 
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v2
@@ -30,6 +35,14 @@ jobs:
     - name: Terraform Plan (Destroy)
       run: terraform plan -destroy -out=tfplan
 
+    - name: Verify Plan File
+      run: test -f tfplan
+
+    - name: Output Plan for Debugging
+      run: |
+        echo "== Plan Output =="
+        terraform show -json tfplan || echo "Error parsing plan"
+        
     - name: Terraform Apply (Destroy)
-      if: ${{ github.event.inputs.confirm_destroy == 'yes' }} # Condicional para evitar ejecuciones accidentales
+      if: ${{ github.event.inputs.confirm_destroy == 'yes' }}
       run: terraform apply -auto-approve tfplan
